Fix actions config

diff --git a/.github/workflows/blank.yml b/.github/workflows/blank.yml
--- a/.github/workflows/blank.yml
+++ b/.github/workflows/blank.yml
@@ -57,4 +57,9 @@ jobs:
     steps:
       - name: Print CI status
         run: |
-          echo "Status of CI pipelin: ${{ needs.build.result }}"
+          if [ "${{ needs.build.outcome}}" != "success" ]; then
+            echo "Build failed! Status of CI pipeline: ${{ needs.build.outcome }}"
+            exit 1
+          else
+            echo "Build secceeded! Status or CI pipeline: $ {{ needs.build.outcome }}"
+          fi
